version: '3.8'

services:
  osint-app:
    build: .
    ports:
      - "7860:7860"
    environment:
      # Terabox Cookie'leri buraya
      - TERABOX_COOKIES=${TERABOX_COOKIES}
      - ALIST_ADMIN_USER=admin
      - ALIST_ADMIN_PASSWORD=${ALIST_PASSWORD:-admin123}
    volumes:
      - terabox_data:/home/user/terabox_data
    restart: unless-stopped

volumes:
  terabox_data:
