services:
  - type: web
    name: osint-terabox
    runtime: docker
    plan: standard
    envVars:
      - key: TERABOX_COOKIES
        sync: false  # Sen gireceksin Render panelinden
      - key: ALIST_ADMIN_USER
        value: admin
      - key: ALIST_ADMIN_PASSWORD
        generateValue: true  # Otomatik şifre
      - key: ALIST_JWT_SECRET
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true
