# OSINT kategorileri — path_keyword yerel taramada dosya yolunda süzülür (alt klasör/dosya adı).
# Tüm görünen isimler Türkçedir.

SKILL_GROUP_LABELS_TR = {
    "discord": "Discord",
    "telegram": "Telegram",
    "slack": "Slack",
    "email": "E-posta",
    "phone": "Telefon & GSM",
    "social": "Sosyal medya",
    "cloud": "Bulut & DevOps",
    "wallet": "Kripto cüzdan",
    "network": "Ağ & altyapı",
    "malware": "Zararlı yazılım",
    "gov": "Kamu & resmi kayıt",
    "forum": "Forum & sızıntı listeleri",
    "iot": "IoT & endüstriyel",
    "game": "Oyun hesapları",
    "stream": "Yayın & VOD",
    "retail": "E-ticaret",
    "media": "Basın & medya",
    "education": "Eğitim & Akademik",
    "healthcare": "Sağlık & Tıp",
    "finance": "Finans & Bankacılık",
    "travel": "Seyahat & Ulaşım",
    "dating": "Arkadaşlık & Tanışma",
    "vpn": "VPN Servisleri",
    "proxy": "Proxy Servisleri",
    "voip": "VoIP Servisleri",
    "crypto_exchange": "Kripto Borsaları",
    "darkweb": "Dark Web & Deep Web",
    "pastebin": "Paste Siteleri",
    "leaks": "Veri Sızıntıları",
    "credentials": "Kimlik Bilgileri",
    "api_keys": "API Anahtarları",
    "database": "Veritabanları",
    "source_code": "Kaynak Kodlar",
    "config_files": "Yapılandırma Dosyaları",
    "logs": "Log Dosyaları",
    "backups": "Yedekler",
}

# Grup ipuçları: skill seçildiğinde yol süzgeci «path_keyword» ile nasıl eşleşir + ne tür veri.
SKILL_GROUP_HINTS_TR = {
    "discord": "Dosya adında 'discord' geçenleri ara. Discord hesap anahtarları, sunucular, botlar ve sohbet yedekleri.",
    "telegram": "Dosya adında 'telegram' geçenleri ara. Telegram kanalları, bot anahtarları, oturum dosyaları ve gruplar.",
    "slack": "Dosya adında 'slack' geçenleri ara. Slack iş alanları, kanallar, uygulama anahtarları ve mesaj yedekleri.",
    "email": "Dosya adında 'email' geçenleri ara. E-posta şifreleri, giriş bilgileri, posta kutuları ve abonelik listeleri.",
    "phone": "Dosya adında 'phone' geçenleri ara. Telefon numaraları, SMS doğrulama kodları, operatör kayıtları ve IMEI numaraları.",
    "social": "Dosya adında 'social' geçenleri ara. Sosyal medya hesapları (Twitter, Instagram, TikTok), takipçiler ve mesajlar.",
    "cloud": "Dosya adında 'cloud' geçenleri ara. Bulut hesap anahtarları (AWS, Azure, Google Cloud), sunucular ve depolama alanları.",
    "wallet": "Dosya adında 'wallet' geçenleri ara. Kripto para cüzdan anahtarları, seed kelimeler, borsa hesapları ve işlem kayıtları.",
    "network": "Dosya adında 'network' geçenleri ara. IP adresleri, domain kayıtları, sunucular, proxy'ler ve ağ bağlantı bilgileri.",
    "malware": "Dosya adında 'malware' geçenleri ara. Virüs ve trojen logları, çalıntı veriler, zararlı yazılım analizleri.",
    "gov": "Dosya adında 'gov' geçenleri ara. Devlet kayıtları, ihaleler, araç plakaları, mahkeme kararları ve resmi belgeler.",
    "forum": "Dosya adında 'forum' geçenleri ara. Forum hesapları, kullanıcı şifreleri, karanlık pazar listeleri ve kullanıcı verileri.",
    "iot": "Dosya adında 'iot' geçenleri ara. Akıllı cihazlar, kameralar, router'lar, ev otomasyonu ve endüstriyel sistemler.",
    "game": "Dosya adında 'game' geçenleri ara. Oyun hesapları (Steam, Epic, PlayStation), oyun anahtarları ve oyuncu verileri.",
    "stream": "Dosya adında 'stream' geçenleri ara. Yayın platformları (Twitch, YouTube), canlı yayınlar, sohbetler ve içerikler.",
    "retail": "Dosya adında 'retail' geçenleri ara. Alışveriş siparişleri, ödeme kartları, mağaza hesapları ve müşteri verileri.",
    "media": "Dosya adında 'media' geçenleri ara. Haberler, TV kanalları, podcast'ler, video içerikleri ve medya dosyaları.",
    "education": "Dosya adında 'education' geçenleri ara. Öğrenci kayıtları, akademik veriler, kurs bilgileri ve eğitim platformları.",
    "healthcare": "Dosya adında 'healthcare' geçenleri ara. Hasta kayıtları, tıbbi raporlar, ilaç bilgileri ve sağlık sigortası verileri.",
    "finance": "Dosya adında 'finance' geçenleri ara. Banka hesapları, kredi kartları, finansal işlemler ve borsa verileri.",
    "travel": "Dosya adında 'travel' geçenleri ara. Uçak biletleri, otel rezervasyonları, pasaport bilgileri ve seyahat planları.",
    "dating": "Dosya adında 'dating' geçenleri ara. Arkadaşlık uygulaması hesapları, profiller, mesajlar ve eşleşme verileri.",
    "vpn": "Dosya adında 'vpn' geçenleri ara. VPN hesapları, sunucu listeleri, yapılandırmalar ve bağlantı logları.",
    "proxy": "Dosya adında 'proxy' geçenleri ara. Proxy sunucuları, IP listeleri, yapılandırmalar ve erişim kayıtları.",
    "voip": "Dosya adında 'voip' geçenleri ara. VoIP hesapları, arama kayıtları, numara listeleri ve yapılandırma dosyaları.",
    "crypto_exchange": "Dosya adında 'crypto_exchange' geçenleri ara. Kripto borsası hesapları, API anahtarları, işlem geçmişi ve bakiye bilgileri.",
    "darkweb": "Dosya adında 'darkweb' geçenleri ara. Dark web market listeleri, .onion siteleri, underground forumlar ve illegal veriler.",
    "pastebin": "Dosya adında 'pastebin' geçenleri ara. Paste site paylaşımları, sızdırılmış veriler, kod parçaları ve metin arşivleri.",
    "leaks": "Dosya adında 'leaks' geçenleri ara. Sızdırılmış veritabanları, hack sonuçları, data dump'ları ve sızıntı listeleri.",
    "credentials": "Dosya adında 'credentials' geçenleri ara. Kullanıcı adları, şifreler, tokenlar, oturumlar ve kimlik doğrulama bilgileri.",
    "api_keys": "Dosya adında 'api_keys' geçenleri ara. API anahtarları, secret tokenlar, uygulama kimlikleri ve erişim kodları.",
    "database": "Dosya adında 'database' geçenleri ara. Veritabanı dump'ları, SQL çıktıları, tablo yapıları ve kayıt dosyaları.",
    "source_code": "Dosya adında 'source_code' geçenleri ara. Kaynak kod dosyaları, proje arşivleri, repository'ler ve yazılım kodları.",
    "config_files": "Dosya adında 'config_files' geçenleri ara. Yapılandırma dosyaları, ayarlar, .env dosyaları ve sistem konfigürasyonları.",
    "logs": "Dosya adında 'logs' geçenleri ara. Sistem logları, erişim kayıtları, hata raporları ve aktivite günlükleri.",
    "backups": "Dosya adında 'backups' geçenleri ara. Yedek dosyalar, backup arşivleri, tarihsel kopyalar ve restore noktaları.",
}

_THEMES = {
    "discord": [
        "Discord token arşivi",
        "Sunucu (guild) istihbarat akışları",
        "Webhook arşivleri",
        "OAuth oturum paketleri",
        "Bot izin haritaları",
        "İstemci modifikasyonu örnekleri",
        "Ses uç noktası meta verisi",
        "Sahne kanalı kayıt dizinleri",
        "Forum konu dışa aktarımları",
        "Davet çözümleyici önbelleği",
        "Sunucu şablon yedekleri",
        "Uygulama kimlik listeleri",
        "DM geçmişi dump'ları",
        "Emoji koleksiyon arşivleri",
        "Bans/Kicks kayıtları",
        "Boost ödeme bilgileri",
        "Nitro abonelik verileri",
        "Server widget ayarları",
        "Integration tokenları",
        "Audit log exportları",
    ],
    "telegram": [
        "Kanal dizin indeksi",
        "Bot token sızıntıları",
        "Grup davet haritaları",
        "Çıkartma paketi meta verisi",
        "MTProto vekil günlükleri",
        "Oturum dizgesi dökümleri",
        "Yönetici kadro dosyaları",
        "İletilen medya önbelleği",
        "Kullanıcı adı geçmişi",
        "Telefon maskesi listeleri",
        "TDATA arşivleri",
        "Bulut sohbet dışa aktarımları",
        "Secret chat oturumları",
        "2FA recovery kodları",
        "Passport verileri",
        "Instant View cache",
        "Voice chat kayıtları",
        "Poll sonuçları",
        "Quiz cevapları",
        "Reactions exportları",
    ],
    "slack": [
        "Çalışma alanı keşfi",
        "Uygulama token paketleri",
        "Kanal dışa aktarma tohumları",
        "Paylaşılan dosya indeksleri",
        "Kurumsal Grid haritaları",
        "İş akışı webhook günlükleri",
        "Misafir hesap listeleri",
        "Özel emoji setleri",
        "Huddle meta verisi",
        "SSO örnek iddiaları",
        "Bolt uygulama sırları",
        "Denetim günlüğü parçaları",
        "Scheduled mesajlar",
        "Reminder listeleri",
        "Status emoji ayarları",
        "DND geçmişi",
        "Canvas dokümanları",
        "Clip video metadatası",
        "MFA backup kodları",
        "Discovery listesi",
    ],
    "email": [
        "SMTP kimlik bilgisi setleri",
        "Gelen kutusu toplama paketleri",
        "Takma ad yönlendirme haritaları",
        "Bülten abone veritabanları",
        "Kurumsal dizin dökümleri",
        "IMAP oturum kalıntıları",
        "MX keşif anlık görüntüleri",
        "SPF/DMARC numaralandırmaları",
        "Catch-all deneme kayıtları",
        "Geçici e-posta alan listeleri",
        "OAuth posta onayı izleri",
        "MIME başlık korpusu",
        "DKIM public keyleri",
        "SMTP submission logları",
        "Mail routing tabloları",
        "Exchange GAL exportları",
        "Gmail label yapıları",
        "Outlook PST analizi",
        "Thunderbird profilleri",
        "Apple Mail akıllı posta kutuları",
    ],
    "phone": [
        "SS7 sonda sonuçları",
        "HLR sorgu önbelleği",
        "Operatör MCC/MNC haritaları",
        "SIM değişim olay günlükleri",
        "OTP yakalama örnekleri",
        "RCS parmak izi veritabanları",
        "Numara tanıma tarzı indeksler",
        "WhatsApp JID köprüleri",
        "SMS ağ geçidi kimlikleri",
        "MVNO müşteri çıktıları",
        "Numara taşıma talep günlükleri",
        "IMEI/TAC sicilleri",
        "Voicemail PIN kırılmış",
        "Signal kayıt kodları",
        "Telegram SMS kodları",
        "Viber aktivasyonları",
        "LINE tokenları",
        "WeChat mini program IDleri",
        "KakaoTalk kullanıcıları",
        "Zalo telefon eşleştirmeleri",
    ],
    "social": [
        "Profil kullanıcı adı haritaları",
        "Takipçi grafik tohumları",
        "Hikâye arşiv yansımaları",
        "Kısa video ses parmak izleri",
        "Biyografi link yönlendirme zincirleri",
        "Onaylı rozet listeleri",
        "Reklam kütüphanesi anlık görüntüleri",
        "Yorum duygu korpusu",
        "Canlı yayın sohbet günlükleri",
        "Çapraz platform kimlik bağları",
        "Gölge yasaklama test sonuçları",
        "İçerik ücreti ödeme kimlikleri",
        "Arkadaş/Follower analizi",
        "Beğeni/Engagement geçmişi",
        "Hashtag kullanım istatistikleri",
        "Coğrafi etiket haritaları",
        "Social graph görselleştirmeleri",
        "Influencer takip listeleri",
        "Brand mention kayıtları",
        "Sentiment analysis sonuçları",
    ],
    "cloud": [
        "S3 kova numaralandırmaları",
        "Azure Blob yanlış yapılandırmaları",
        "GCP proje meta verisi",
        "IAM ilkesi dışa aktarımları",
        "K8s gizli manifestleri",
        "Terraform durum sızıntıları",
        "CI/CD token paketleri",
        "Konteyner kayıt indeksleri",
        "Sunucusuz ortam dökümleri",
        "VPC akış özetleri",
        "CloudTrail olay örnekleri",
        "WAF atlama notları",
        "Lambda environment değişkenleri",
        "EC2 instance metadata",
        "RDS connection stringleri",
        "DynamoDB tablo şemaları",
        "CloudFront distribution IDleri",
        "SQS queue URL'leri",
        "SNS topic ARN'leri",
        "API Gateway stage değişkenleri",
    ],
    "wallet": [
        "Tohum cümle sözlük listeleri",
        "Keystore JSON paketleri",
        "Donanım cüzdan seri numaraları",
        "DEX onay günlükleri",
        "Köprü işlem izleri",
        "NFT koleksiyon telif kayıtları",
        "Karıştırıcı çıkış kümeleri",
        "Borsa KYC parçaları",
        "Soğuk depo etiketleri",
        "Çoklu imza imzacı haritaları",
        "Zincir RPC anahtar sızıntıları",
        "DeFi pozisyon anlık görüntüleri",
        "HD cüzdan türev yolları",
        "BIP39 mnemonic listeleri",
        "Ledger cihaz yedekleri",
        "Trezor wallet exportları",
        "MetaMask şifrelenmiş vault",
        "Phantom Solana cüzdanları",
        "Rainbow Ethereum cüzdanları",
        "Trust Wallet yedekleri",
    ],
    "network": [
        "Pasif DNS geçmişi",
        "Sertifika şeffaflık zincirleri",
        "ASN komşuluk grafikleri",
        "BGP ele geçirme zaman çizelgeleri",
        "Tor röle parmak izleri",
        "Konut vekili havuzları",
        "CDN kaynak sızıntıları",
        "Ters DNS yürüyüşleri",
        "Port tarama toplu sonuçları",
        "Güvenlik duvarı kural dökümleri",
        "WireGuard anahtar çiftleri",
        "ZeroTier ağ haritaları",
        "OpenVPN client konfigürasyonları",
        "IPsec PSK listeleri",
        "GRE tunnel endpointleri",
        "VXLAN network IDleri",
        "MPLS label haritaları",
        "OSPF area topolojileri",
        "NetFlow export analizi",
        "sFlow sampling verileri",
    ],
    "malware": [
        "Stealer günlük normalleştirilmiş",
        "RAT C2 panel dökümleri",
        "Yükleyici kampanya IOC'leri",
        "Oltalama kiti arşivleri",
        "Sömürü kiti iniş setleri",
        "Şifreleyici oluşturucu çıktıları",
        "Tuş kaydedici yapılandırma tohumları",
        "Botnet düğüm listeleri",
        "Dropper PDB yolları",
        "Kum havuzu davranış JSON'u",
        "YARA kural eşleşmeleri",
        "Mutex dize korpusu",
        "Cobalt Strike beaconları",
        "Metasploit oturumları",
        "Empire agent listeleri",
        "PoshC2 implant konfigürasyonları",
        "Gootkit web injectleri",
        "Dridex botnet IDleri",
        "TrickBot command store",
        "Qakbot C2 modülleri",
    ],
    "gov": [
        "Kamu ihale indeksleri",
        "Kadastro parsel haritaları",
        "Araç tescil örnekleri",
        "Mahkeme dava meta verisi",
        "Seçmen listesi parçaları",
        "Vergi numarası biçim rehberleri",
        "İzin tarayıcı çıktıları",
        "Bilgi edinme (FOIA) paketleri",
        "Yaptırım listesi yansımaları",
        "Ticaret sicili çıkarımları",
        "Gümrük beyanname formları",
        "Sınır geçiş günlükleri",
        "Pasaport MRZ verileri",
        "Kimlik kartı seri numaraları",
        "Adli sicil kayıtları",
        "Tapu mülkiyet geçmişi",
        "Belediye ruhsat dosyaları",
        "SSK/SGK prim kayıtları",
        "Vergi dairesi borç yapılandırmaları",
        "Noter işlem kayıtları",
    ],
    "forum": [
        "Bülten panosu kullanıcı haritaları",
        "vBulletin tablo dökümleri",
        "XenForo oturum tohumları",
        "phpBB özel iletiler",
        "Karanlık pazar satıcı kartları",
        "Kimlik yapıştırma indeksleri",
        "Combo liste normalleştiricileri",
        "Kırma forumu konu dizileri",
        "Davetli izleyici haritaları",
        "Rep puanı geçmişleri",
        "İmza bloğu zararlı yazılımı",
        "Moderatör işlem günlükleri",
        "MyBB reputation sistemi",
        "SMF board yönetimi",
        "Discourse badge dağıtımları",
        "Flarum etiket yapısı",
        "NodeBB kullanıcı grupları",
        "Vanilla reactions kayıtları",
        "PunBB grup izinleri",
        "FluxBB ban listesi",
    ],
    "iot": [
        "Kamera varsayılan kimlikleri",
        "Yönlendirici yapılandırma yedekleri",
        "MQTT konu hasatları",
        "Zigbee koordinatör haritaları",
        "Akıllı kilit ürün yazılımı kimlikleri",
        "Endüstriyel PLC etiketleri",
        "GPS takipçi IMEI havuzları",
        "Filo telematik akışları",
        "BLE işaret UUID'leri",
        "Home Assistant anlık görüntüleri",
        "IP kamera RTSP uç noktaları",
        "SCADA HMI dışa aktarımları",
        "Modbus register haritaları",
        "OPC UA server listeleri",
        "CAN bus message IDleri",
        "Profinet device konfigürasyonları",
        "EtherNet/IP assembly instance'ları",
        "BACnet object identifierları",
        "KNX group adresleri",
        "LonWorks network variableları",
    ],
    "game": [
        "Steam oturum çıktıları",
        "Epic Games hesap dökümleri",
        "Riot istemci günlükleri",
        "Minecraft sunucu listeleri",
        "Roblox oturum kalıntıları",
        "Battle.net launcher yedekleri",
        "Xbox Live profil önbelleği",
        "PlayStation Network kimlik haritası",
        "Ubisoft Connect token arşivi",
        "GOG Galaxy oturum dosyaları",
        "EA App kimlik dökümleri",
        "Battlefield sunucu ping listeleri",
        "Valorant maç geçmişi",
        "League of Legends MMR değerleri",
        "CS:GO skin envanteri",
        "Dota 2 maç IDleri",
        "PUBG telemetry verileri",
        "Apex Legends rank kademeleri",
        "Genshin Impact wish geçmişi",
        "Honkai Star Rail warp kayıtları",
    ],
    "stream": [
        "Twitch kanal meta arşivi",
        "YouTube canlı sohbet dökümleri",
        "Kick yayıncı panel günlükleri",
        "Facebook Gaming yayın meta verisi",
        "Trovo abonelik exportları",
        "DLive işlem günlükleri",
        "StreamElements komut arşivi",
        "OBS sahne yapılandırma yedekleri",
        "Restream RTMP uç noktaları",
        "Vimeo canlı etkinlik erişimleri",
        "TikTok LIVE hediye logları",
        "LinkedIn Live davet zincirleri",
        "Mixer legacy arşivleri",
        "Periscope yayın geçmişi",
        "Caffeine yayın meta verisi",
        "YouNow yayın kayıtları",
        "Bigo Live gift listeleri",
        "Tango yayın cacheleri",
        "Nonolive yayıncı profilleri",
        "LiveMe diamond işlem kayıtları",
    ],
    "retail": [
        "Amazon sipariş CSV arşivleri",
        "eBay teklif geçmişi dökümleri",
        "Etsy mağaza müşteri listeleri",
        "Trendyol satıcı paneli özeti",
        "Hepsiburada iade talep günlükleri",
        "Shopify müşteri exportları",
        "WooCommerce sipariş XML dosyaları",
        "Stripe ödeme webhook günlükleri",
        "PayPal işlem CSV arşivleri",
        "AliExpress kargo takip listeleri",
        "Zalando üyelik indeksi",
        "n11 fatura meta verisi",
        "Gittigidiyor yorum analizi",
        "Amazon ASIN katalogu",
        "eBay item specifics",
        "Shopify product metafieldları",
        "WooCommerce coupon kodları",
        "BigCommerce customer grupları",
        "Magento quote IDleri",
        "PrestaShop cart rule listeleri",
    ],
    "media": [
        "RSS haber akışı indeksleri",
        "Podcast RSS abone listeleri",
        "Basın bülteni e-posta arşivleri",
        "IPTV kanal M3U listeleri",
        "Dijital gazete abonelik kimlikleri",
        "Basın ajansı foto metadata",
        "Yerel radyo frekans envanteri",
        "TV rehberi EPG çıktıları",
        "Haber sitesi yorum dökümleri",
        "Muhabir kaynak notları",
        "Editör CMS oturum günlükleri",
        "Video CDN URL haritaları",
        "Wire service yayın akışları",
        "Satellite downlink frekansları",
        "Radio tower koordinatları",
        "Newsroom Slack entegrasyonları",
        "Content management workflow",
        "Digital asset management IDleri",
        "Media monitoring alert kuralları",
        "Social media publishing queue",
    ],
    "education": [
        "Öğrenci bilgi sistemi kayıtları",
        "Transkript ve not geçmişi",
        "Akademik personel listeleri",
        "Ders programı ve müfredat",
        "Uzaktan eğitim platform oturumları",
        "LMS kullanıcı aktivite logları",
        "Sınav sonuçları ve analitikleri",
        "Öğrenci değerlendirme raporları",
        "Eğitim materyali erişim kayıtları",
        "Kütüphane ödünç alma sistemleri",
        "Yurt ve pansiyon kayıtları",
        "Burs ve finansman verileri",
        "Akademik yayın ve atıf indeksleri",
        "Ders kayıt ve add/drop işlemleri",
        "Mezuniyet ve diploma doğrulama",
        "Staj ve işyeri eğitimi kayıtları",
        "Akreditasyon denetim dosyaları",
        "Akademik takvim ve etkinlikler",
        "Öğrenci kulüp üyelik listeleri",
        "Siber laboratuvar erişim logları",
    ],
    "healthcare": [
        "Hasta kayıt ve kimlik bilgileri",
        "Elektronik reçete sistemleri",
        "Tıbbi görüntüleme arşivleri",
        "Laboratuvar test sonuçları",
        "Hasta takip ve monitorizasyon",
        "Sağlık sigortası poliçeleri",
        "Randevu ve planlama sistemleri",
        "İlaç stok ve eczane kayıtları",
        "Tıbbi cihaz konfigürasyonları",
        "Klinik araştırma veri setleri",
        "Hastane yönetim sistemi logları",
        "Acil servis triyaj kayıtları",
        "Ameliyat ve prosedür raporları",
        "Hasta ödemeleri ve faturalama",
        "Sağlık çalışanı vardiya planları",
        "Epidemiyolojik takip verileri",
        "Aşı kayıt ve takip sistemleri",
        "Tele-sağlık oturum kayıtları",
        "Tıbbi transkripsiyon dosyaları",
        "Biyobank ve örnek yönetimi",
    ],
    "finance": [
        "Banka hesap ekstreleri",
        "Kredi kartı işlem kayıtları",
        "Wire transfer SWIFT mesajları",
        "Online bankacılık oturum logları",
        "ATM işlem ve konum kayıtları",
        "Yatırım portföyü pozisyonları",
        "Forex ve döviz işlem geçmişi",
        "Bono ve tahvil sahiplik kayıtları",
        "Kredi ve mortgage başvuruları",
        "Risk yönetimi ve skorlama",
        "Müşteri risk profili analizleri",
        "Hesap açılış ve kapatış belgeleri",
        "Vergi beyanname ve raporları",
        "Muhasebe genel mizan kayıtları",
        "Fatura ve tahsilat yönetimi",
        "POS terminal işlem logları",
        "Mobile banking cihaz kayıtları",
        "Fraud tespit ve AML kayıtları",
        "Yatırım danışmanlığı notları",
        "Sigorta poliçe ve hasar kayıtları",
    ],
    "travel": [
        "Uçak bileti rezervasyon PNR",
        "Otel konaklama kayıtları",
        "Araç kiralama sözleşmeleri",
        "Pasaport ve vize başvuruları",
        "Seyahat sigortası poliçeleri",
        "Tur paketi rezervasyonları",
        "Cruise gemi yolcu listeleri",
        "Tren ve otobüs biletleri",
        "Havalimanı lounge erişimleri",
        "Seyahat sadakat programı puanları",
        "Gümrük beyanname ve giriş/çıkış",
        "Bagaj takip ve kayıp eşya",
        "Seyahat acentesi müşteri listesi",
        "Grup tur katılımcıları",
        "Konferans ve fuar katılım kayıtları",
        "VIP concierge servis talepleri",
        "Seyahat iptal ve iade işlemleri",
        "Mobil boarding pass kayıtları",
        "Seyahat harcama ve masraf raporları",
        "GPS takipli araç filo kayıtları",
    ],
    "dating": [
        "Tinder swipe ve match geçmişi",
        "Bumble mesaj ve sohbet logları",
        "Hinge profil ve tercih verileri",
        "OkCupid kişilik test sonuçları",
        "Plenty of Fish kullanıcı aramaları",
        "Match.com abonelik bilgileri",
        "Badoo konum ve radar geçmişi",
        "Grindr profil ve tarama kayıtları",
        "Her kullanıcı etkileşim logları",
        "Coffee Meets Bagel match analizi",
        "The League onay ve bekleme listesi",
        "Happn geçiş ve karşılaşma kayıtları",
        "Zoosk davranışsal matchmaking",
        "eHarmony uyumluluk skorları",
        "JDate dini tercih filtreleri",
        "Christian Mingle inanç profilleri",
        "Muslima kültürel tercih kayıtları",
        "BLK etnik köken filtrelemeleri",
        "BLK etnik topluluk etkinlikleri",
        "BLK sosyal etkileşim haritaları",
    ],
    "vpn": [
        "OpenVPN sunucu konfigürasyonları",
        "WireGuard peer public keyleri",
        "IPSec/L2TP bağlantı logları",
        "NordVPN oturum kimlik doğrulama",
        "ExpressVPN sunucu lokasyon listesi",
        "Surfshark CleanWeb filtre kayıtları",
        "CyberGhost no-log politikası",
        "ProtonVPN Secure Core bağlantıları",
        "Mullvad anonim hesap numaraları",
        "PIA port forwarding ayarları",
        "Hotspot Shield bandwidth kullanımı",
        "TunnelBear vigilance mod logları",
        "Windscribe R.O.B.E.R.T. kuralları",
        "IPVanish SOCKS5 proxy yapılandırma",
        "VyprVPN Chameleon protokol kayıtları",
        "TorGuard stealth proxy bağlantıları",
        "PrivateVPN kill switch aktivasyonları",
        "Atlas VPN SafeBrowse filtre logları",
        "UltraVPN sunucu yük dengeleme",
        "HMA VPN IP değişim zaman çizelgesi",
    ],
    "proxy": [
        "HTTP/HTTPS proxy liste ve portları",
        "SOCKS4/5 proxy yapılandırma",
        "Squid proxy erişim logları",
        "HAProxy yük dengeleme kuralları",
        "Nginx reverse proxy upstream",
        "Apache mod_proxy konfigürasyonları",
        "Residential proxy IP havuzları",
        "Datacenter proxy subnet haritaları",
        "Rotating proxy API endpointleri",
        "Backconnect proxy oturum IDleri",
        "Elite proxy anonimlik seviyeleri",
        "Transparent proxy X-Forwarded-For",
        "Proxy chaining ve cascade yapılandırma",
        "PAC (Proxy Auto-Config) dosyaları",
        "WPAD (Web Proxy Auto-Discovery)",
        "Burp Suite upstream proxy chain",
        "Charles proxy SSL certificate",
        "Fiddler proxy session arşivleri",
        "OWASP ZAP proxy history",
        "mitmproxy flow kayıtları",
    ],
    "voip": [
        "SIP trunk yapılandırma kayıtları",
        "Asterisk CDR (Call Detail Records)",
        "FreePBX extension ve dahililer",
        "Twilio SIP domain ayarları",
        "Vonage API key ve secret",
        "RingCentral oturum tokenları",
        "8x8 santral konfigürasyon yedekleri",
        "3CX phone system kullanıcı listesi",
        "Avaya PBX station yapılandırması",
        "Cisco CUCM kullanıcı profilleri",
        "Yeastar S-Series yedek dosyaları",
        "Grandstream UCM arama kayıtları",
        "Vodia PBX multi-tenant ayarları",
        "FusionPBX domain yapılandırmaları",
        "Kamailio SIP routing scriptleri",
        "OpenSIPS load balancing kuralları",
        "FreeSWITCH dialplan XML dosyaları",
        "WebRTC gateway tokenları",
        "RTCPeerConnection ICE candidate",
        "VoIP QoS ve codec tercihleri",
    ],
    "crypto_exchange": [
        "Binance API key ve secret",
        "Coinbase Pro trading history",
        "Kraken deposit/withdrawal kayıtları",
        "Bitfinex margin pozisyonları",
        "KuCoin lending ve staking",
        "OKX futures trading logları",
        "Bybit copy trading takipçileri",
        "Huobi OTC işlem geçmişi",
        "Gate.io HODL & Earn kayıtları",
        "Crypto.com Visa kart işlemleri",
        "FTX (legacy) account balances",
        "Bittrex API v3 key permissions",
        "Poloniex margin borçlanma",
        "Gemini ActiveTrader order book",
        "Bitstamp liquitidy metrics",
        "BitMEX leaderboard positions",
        "Deribit options expiry takvimi",
        "dYdX perpetual funding rate",
        "Uniswap v3 LP pozisyon NFT",
        "SushiSwap Onsen farm APY",
    ],
    "darkweb": [
        "Tor hidden service .onion listeleri",
        "I2P eepsite address book",
        "ZeroNet site zeronet addressleri",
        "Freenet freesite keyleri",
        "Dark web marketplace vendorları",
        "Cryptocurrency escrow servisleri",
        "Carding shop CC dump listeleri",
        "Hacking forum üye veritabanları",
        "Malware-as-a-Service panel girişleri",
        "DDoS stresser API keyleri",
        "Exploit kit satış listeleri",
        "Ransomware builder lisansları",
        "Bulletproof hosting müşteri kayıtları",
        "Counterfeit document satıcıları",
        "Drug marketplace pazaryeri",
        "Weapons trafficking kanalları",
        "Human trafficking veri izleri",
        "CSAM blockchain metadata",
        "Money laundering mixer servisleri",
        "Hitman-for-hire site listeleri",
    ],
    "pastebin": [
        "Pastebin.com raw paste URLleri",
        "Ghostbin encrypted paste şifreleri",
        "Hastebin syntax highlighted kodlar",
        "PrivateBin zero-knowledge yapılandırma",
        "0bin client-side encryption keyleri",
        "Rentry.co markdown paste arşivi",
        "JustPaste.it görsel ve metin içerikleri",
        "Paste.ee API upload kayıtları",
        "ControlC text paste metadata",
        "Ubuntu Pastebin yaşam süresi ayarları",
        "GitHub Gist secret revision history",
        "GitLab Snippet visibility settings",
        "Bitbucket Snippet fork chain",
        "SourceForge pastebin alternatifleri",
        "JSFiddle saved fiddle kodları",
        "CodePen pen source exportları",
        "Stack Overflow snippet paylaşımları",
        "Ideone compiler execution logları",
        "Pastebin.pl proxy bypass yapılandırma",
        "DPaste Django paste uygulama kayıtları",
    ],
    "leaks": [
        "Veritabanı dump SQL dumps",
        "Combo list username:password",
        "Dehashed search query logları",
        "Have I Been Pwned breach kayıtları",
        "Intelligence X search history",
        "Shodan host geçmişi arşivi",
        "Censys certificate transparency",
        "Spyse subdomain enumeration",
        "Fofa dork search sonuçları",
        "BinaryEdge internet scan verileri",
        "Onyphe cyber defense platform",
        "Greynoise noise ve riot IP listeleri",
        "VirusTotal file submission metadata",
        "URLScan.io submission kayıtları",
        "AlienVault OTX pulse gözlemleri",
        "MalwareBazaar sample yorumları",
        "ThreatFox IOC indicator listeleri",
        "Abuse.ch SSL Blacklist",
        "EmergingThreats IDS ruleset",
        "Proofpoint EmergingThreats IP listesi",
    ],
    "credentials": [
        "Username:password kombinasyon listeleri",
        "Email:password credential pairs",
        "Hash cracked password plaintextler",
        "Sosyal mühendislik mağduru kimlikler",
        "Phishing kit captured credentiallar",
        "Keylogger captured form verileri",
        "Browser saved password exports",
        "Password manager vault exportları",
        "SSH private key passphrase'leri",
        "SSL certificate private keyleri",
        "JWT token secret ve payload",
        "OAuth refresh token döngüleri",
        "SAML assertion ve attribute",
        "Kerberos ticket ve session",
        "NTLM hash ve challenge-response",
        "LDAP bind credential kayıtları",
        "RADIUS shared secret yapılandırma",
        "TOTP seed ve backup kodlar",
        "Hardware token seed dosyaları",
        "Biometric template hashleri",
    ],
    "api_keys": [
        "REST API key ve secret pairs",
        "GraphQL endpoint authentication",
        "gRPC API token ve metadata",
        "Webhook secret ve signature",
        "SDK client ID ve client secret",
        "Server-to-server API credential",
        "Mobile app API key embedding",
        "Third-party integration tokenları",
        "SaaS platform API access",
        "Cloud service IAM API keys",
        "Payment gateway API secret",
        "SMS gateway API credential",
        "Email service API key",
        "Storage service API token",
        "Analytics platform API access",
        "Social media API key limit",
        "Search engine API quota",
        "Maps ve geolocation API key",
        "Machine learning API endpoint",
        "Blockchain node API access",
    ],
    "database": [
        "MySQL/MariaDB dump dosyaları",
        "PostgreSQL pg_dump arşivleri",
        "MongoDB BSON exportları",
        "Redis RDB snapshot dosyaları",
        "Elasticsearch index mapping",
        "Cassandra CQL schema export",
        "Neo4j graph database dump",
        "SQLite .db ve .sqlite dosyaları",
        "Microsoft SQL Server .bak",
        "Oracle RMAN backup parçaları",
        "Firebase Realtime DB JSON",
        "Firestore collection exportları",
        "DynamoDB table item JSON",
        "Cosmos DB SQL API kayıtları",
        "Couchbase bucket dump",
        "InfluxDB time-series data",
        "Prometheus TSDB blockları",
        "ClickHouse tablo exportları",
        "Snowflake warehouse query history",
        "BigQuery dataset metadata",
    ],
    "source_code": [
        "Git repository .git dizini",
        "SVN repository .svn folders",
        "Mercurial .hg store dosyaları",
        "CVS CVSROOT yapılandırması",
        "GitHub repo private clone URL",
        "GitLab project CI/CD değişkenleri",
        "Bitbucket repository webhook",
        "SourceForge project download",
        "Codeberg repo access logları",
        "Gitea/Gogs repository ayarları",
        "Jenkins pipeline groovy script",
        "GitHub Actions workflow YAML",
        "GitLab CI .gitlab-ci.yml",
        "Travis CI .travis.yml config",
        "CircleCI config.yml dosyası",
        "Azure Pipelines YAML tanımı",
        "Dockerfile ve docker-compose",
        "Kubernetes manifest YAML",
        "Terraform .tfstate ve modül",
        "Ansible playbook ve inventory",
    ],
    "config_files": [
        ".env environment değişkenleri",
        "config.json yapılandırma",
        "settings.xml XML config",
        "application.properties Java",
        "appsettings.json .NET",
        "php.ini PHP yapılandırma",
        "web.config IIS ayarları",
        ".htaccess Apache kuralları",
        "nginx.conf Nginx config",
        "httpd.conf Apache config",
        "sshd_config SSH daemon",
        "my.cnf MySQL config",
        "postgresql.conf Postgres",
        "redis.conf Redis ayarları",
        "elasticsearch.yml ES config",
        "kibana.yml Kibana ayarları",
        "logstash.conf LS pipeline",
        "prometheus.yml Prometheus",
        "grafana.ini Grafana config",
        "docker-compose.yml servisler",
    ],
    "logs": [
        "access.log web sunucu erişim",
        "error.log uygulama hataları",
        "syslog sistem olay kayıtları",
        "auth.log kimlik doğrulama",
        "audit.log denetim izleri",
        "application.log yazılım log",
        "debug.log geliştirici log",
        "info.log bilgi seviyesi",
        "warning.log uyarı kayıtları",
        "critical.log kritik olaylar",
        "security.log güvenlik olayları",
        "firewall.log güvenlik duvarı",
        "vpn.log VPN bağlantı kayıtları",
        "dhcp.log IP atama kayıtları",
        "dns.log sorgu logları",
        "mail.log e-posta sunucu",
        "cron.log zamanlanmış görevler",
        "kernel.log çekirdek mesajları",
        "boot.log açılış kayıtları",
        "history.log komut geçmişi",
    ],
    "backups": [
        ".tar.gz arşiv yedekler",
        ".zip sıkıştırılmış yedekler",
        ".7z 7-Zip arşiv formatı",
        ".rar WinRAR arşivleri",
        ".bz2 bzip2 sıkıştırma",
        ".xz XZ Utils arşivleri",
        ".tar POSIX tape arşivi",
        ".bak backup uzantıları",
        ".old eski versiyon dosyaları",
        ".orig orijinal dosya kopyası",
        ".sav save dosya uzantısı",
        ".tmp geçici yedek dosyaları",
        "backup/ dizin yedekleri",
        "old/ eski versiyon klasörü",
        "archive/ arşiv depolama",
        "snapshots/ anlık görüntüler",
        "restore/ geri yükleme noktaları",
        "dump/ veritabanı dökümleri",
        "export/ dışa aktarma yedekleri",
        "snapshot_/ tarihli yedekler",
    ],
}


def _slugify_tr(text: str) -> str:
    _mp = {
        ord("ğ"): "g",
        ord("ü"): "u",
        ord("ş"): "s",
        ord("ö"): "o",
        ord("ç"): "c",
        ord("ı"): "i",
        ord("İ"): "i",
        ord("Ğ"): "g",
        ord("Ü"): "u",
        ord("Ş"): "s",
        ord("Ö"): "o",
        ord("Ç"): "c",
    }
    s = text.translate(_mp).lower()
    out = []
    for c in s:
        if c.isalnum():
            out.append(c)
        elif c in " _-/":
            out.append("_")
    slug = "".join(out)
    while "__" in slug:
        slug = slug.replace("__", "_")
    return slug.strip("_")[:56]


def _build():
    skills = []
    priority = 1
    for keyword, titles in _THEMES.items():
        for title in titles:
            slug = f"{keyword}_{_slugify_tr(title)}"
            gh = SKILL_GROUP_HINTS_TR.get(
                keyword,
                f"Yol veya dosya adında «{keyword}» geçmeli; bu gruba ait dump’lar.",
            )
            skills.append(
                {
                    "id": f"{slug}_{priority}",
                    "name": title,
                    "path_keyword": keyword,
                    "priority": priority,
                    "hint": f"{gh} Bu satır: «{title}».",
                }
            )
            priority += 1
    return skills


DATABASE_SKILLS = _build()

assert len(DATABASE_SKILLS) >= 650, len(DATABASE_SKILLS)
